version: "3"
services:
  db:
    image: "postgres:13-alpine"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=spring_boot_demo_db
    ports:
      - "54320:5432"
