apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-boot-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-boot-demo-app
  template:
    metadata:
      labels:
        app: spring-boot-demo-app
    spec:
      containers:
        - name: spring-boot-demo
          image: ssuraci/spring-boot-demo
          imagePullPolicy: "Never"
          resources:
            requests:
              memory: "512Mi"
              cpu: "500m"
            limits:
              memory: "1024Mi"
              cpu: "1000m"
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: spring-boot-demo-lb
spec:
  type: LoadBalancer
  ports:
   - port: 8088
     targetPort: 8080
  selector:
    app: spring-boot-demo-app      