version: "3"
services:
  
  spring_boot_playground_demo_pgsql:
    image: ssuraci/spring-boot-playground-demo
    environment:
      - DATASOURCE_DRIVER_CLASS_NAME=org.postgresql.Driver
      - DATASOURCE_DIALECT=org.hibernate.dialect.PostgreSQLDialect
      - DATASOURCE_URL=jdbc:postgresql://spring_boot_playground_pgsql_db/${POSTGRES_DB}
      - DATASOURCE_USERNAME=${POSTGRES_USER}
      - DATASOURCE_PASSWORD=${POSTGRES_PASSWORD}        
    profiles:
      - pgsql
    ports:
      - 8080:8080  
    depends_on:    
      - spring_boot_playground_pgsql_db
  
  spring_boot_playground_pgsql_db:
    image: postgres:14-alpine
    environment:
     - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
     - POSTGRES_USER=${POSTGRES_USER}
     - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - 54321:5432
    profiles:
      - pgsql

  spring_boot_playground_demo_mssql:
    image: ssuraci/spring-boot-playground-demo
    environment:
      - DATASOURCE_DRIVER_CLASS_NAME=com.microsoft.sqlserver.jdbc.SQLServerDriver
      - DATASOURCE_DIALECT=org.hibernate.dialect.SQLServerDialect
      - DATASOURCE_URL=jdbc:sqlserver://spring_boot_playground_mssql_db;databaseName=master
      - DATASOURCE_USERNAME=sa
      - DATASOURCE_PASSWORD=${MSSQL_PASSWORD}        
    profiles:
      - mssql
    ports:
      - 8080:8080  
    depends_on:    
      - spring_boot_playground_mssql_db
      
  spring_boot_playground_mssql_db:
    image: "mcr.microsoft.com/mssql/server:2019-CU13-ubuntu-20.04"
    environment:
      - SA_PASSWORD=${MSSQL_PASSWORD}
      - ACCEPT_EULA=Y
    ports:
      - "14330:1433"    
    profiles:
      - mssql
