version: "3"
services:
  spring-boot-playground-demo-pgsql:
    image: spring-boot-playground-demo:0.2.0
    environment:
      - DATASOURCE_DRIVER_CLASS_NAME=org.postgresql.Driver
      - DATASOURCE_DIALECT=org.hibernate.dialect.PostgreSQLDialect
      - DATASOURCE_URL=jdbc:postgresql://spring-boot-playground-pgsql-db/${POSTGRES_DB}
      - DATASOURCE_USERNAME=${POSTGRES_USER}
      - DATASOURCE_PASSWORD=${POSTGRES_PASSWORD}        
    profiles:
      - pgsql
    ports:
      - 8080:8080  
    depends_on:    
      - spring-boot-playground-pgsql-db
  
  spring-boot-playground-pgsql-db:
    image: postgres:15-alpine
    environment:
     - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
     - POSTGRES_USER=${POSTGRES_USER}
     - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - 54321:5432
    profiles:
      - pgsql

  spring-boot-playground-demo-mssql:
    image: spring-boot-playground-demo:0.2.0
    environment:
      - DATASOURCE_DRIVER_CLASS_NAME=com.microsoft.sqlserver.jdbc.SQLServerDriver
      - DATASOURCE_DIALECT=org.hibernate.dialect.SQLServerDialect
      - DATASOURCE_URL=jdbc:sqlserver://spring-boot-playground-mssql-db;databaseName=master
      - DATASOURCE_USERNAME=sa
      - DATASOURCE_PASSWORD=${MSSQL_PASSWORD}        
    profiles:
      - mssql
    ports:
      - 8080:8080  
    depends_on:    
      - spring-boot-playground-mssql-db
      
  spring-boot-playground-mssql-db:
    image: "mcr.microsoft.com/mssql/server:2019-CU13-ubuntu-20.04"
    environment:
      - SA_PASSWORD=${MSSQL_PASSWORD}
      - ACCEPT_EULA=Y
    ports:
      - "14330:1433"    
    profiles:
      - mssql
