kind: ConfigMap 
apiVersion: v1 
metadata:
  name: spring-boot-demo-playground-cm  
data:
  # Configuration values can be set as key-value properties
  DATASOURCE_DRIVER_CLASS_NAME: org.postgresql.Driver
  DATASOURCE_DIALECT: org.hibernate.dialect.PostgreSQLDialect
  DATASOURCE_URL: jdbc:postgresql://spring-boot-playground-demo-pgsql-db/spring_boot_playground_demo_db
  DATASOURCE_USERNAME: postgres
  DATASOURCE_PASSWORD: postgres 