apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: spring-boot-demo-postgresql
spec:
  replicas: 1
  serviceName: "spring-boot-demo-postgresql"
  selector:
    matchLabels:
      app: spring-boot-demo-postgresql
  template:
    metadata:
      labels:
        app: spring-boot-demo-postgresql
    spec:
      containers:
        - name: postgres
          image: postgres:latest
          imagePullPolicy: "IfNotPresent"
          resources:
            requests:
              memory: "256Mi"
              cpu: "500m"
            limits:
              memory: "510Mi"
              cpu: "1000m"
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: postgres-config
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgresdb
      volumes:
        - name: postgresdb
          persistentVolumeClaim:
            claimName: postgres-pv-claim
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  labels:
    app: spring-boot-demo-postgresql
data:
  POSTGRES_DB: postgresdb
  POSTGRES_USER: postgresadmin
  POSTGRES_PASSWORD: admin123
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: postgres-pv-claim
  labels:
    app: spring-boot-demo-postgresql
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: spring-boot-demo-postgresql
spec:
  type: LoadBalancer
  ports:
   - port: 54321
     targetPort: 5432
  selector:
    app: spring-boot-demo-postgresql      