version: "3"
services:
  test-db:
    image: postgres:14-alpine
    environment:
     - POSTGRES_PASSWORD=postgres
     - POSTGRES_USER=postgres
     - POSTGRES_DB=spring_boot_playground_demo_db
    ports:
      - 54321:5432
